version: 2.1

workflows:
  version: 2
  main:
    jobs:
      - build:
          context: aws

orbs:
  android: circleci/android@0.2.1
  aws-cli: circleci/aws-cli@1.3.2

jobs:
  build:
    working_directory: ~/code/OpenCabProvider
    executor: android/android
    steps:
      - checkout:
          path: ~/code
      - aws-cli/install
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Create release build
          command: ./gradlew assembleDebug
      - run:
          name: Upload build to Firebase
          command: ./gradlew appDistributionUploadDebug
      - run:
          name: Install lftp command line tool
          command: sudo apt-get update && sudo apt-get install lftp
      - run:
          name: Build documentation
          command: ./build-docs.sh
      - run:
          name: Deploy documentation
          command: ./upload-docs.sh
